spring:
  application:
    name: ssm-boot-producer
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml
  pattern:
    console: "%d - %msg%n"
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
   # root: info
#服务监控暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
